FROM python:2.7
WORKDIR /root

COPY waiter.py /tmp
COPY setup.py /tmp
COPY myshell /usr/bin

RUN apt update && apt install -y vim less openssh-server sudo
RUN systemctl enable ssh
RUN mkdir -p /run/sshd

RUN mkdir -pv /root/.ssh
COPY .ssh/* /root/.ssh/
RUN chmod -R 700 .ssh

cmd ["python", "/tmp/waiter.py"]
