FROM python:2.7
WORKDIR /root

COPY waiter.py /tmp
COPY setup.py /tmp

RUN apt update && apt install -y ansible vim less openssh-server
RUN systemctl enable ssh
RUN mkdir -p /run/sshd

RUN mkdir -pv /root/.ssh
COPY .ssh/* /root/.ssh/
RUN chmod -R 700 .ssh

cmd ["python", "/tmp/waiter.py"]
